const { ObjectID } = require("mongodb");

module.exports = [{ imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a41.jpg',
    modelName: 'Samsung Galaxy A41',
    price: null,
    releasedDate: 'Released 2020, May 22',
    batteryCapacity: '3500',
    cpu: '1080 x 2400 pixels, 20:9 ratio (~431 ppi density)',
    ram: '4',
    sim: 'not found',
    screenSize:
     '6.1 inches, 89.8 cm<sup>2</sup> (~85.9% screen-to-body ratio)',
    frontCameraRes:
     '48 MP, f/2.0, 26mm (wide), 1/2.0", 0.8µm, PDAF<br>\n8 MP, f/2.2, 123˚ (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.4, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m21.jpg',
    modelName: 'Samsung Galaxy M21',
    price: null,
    releasedDate: 'Released 2020, March 23',
    batteryCapacity: '6000',
    cpu:
     'Octa-core (4x2.3 GHz Cortex-A73 &amp; 4x1.7 GHz Cortex-A53)',
    ram: '4/6',
    sim:
     'Single SIM (Nano-SIM) or Dual SIM (Nano-SIM, dual stand-by)',
    screenSize: 'Exynos 9611 (10nm)',
    frontCameraRes: '20 MP, f/2.0, 26mm (wide)',
    rearCameraRes:
     '48 MP, f/2.0, 26mm (wide), 1/2.0", 0.8µm, PDAF<br>\n8 MP, f/2.2, 12mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    os: 'Android 10, One UI 2.5',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a11.jpg',
    modelName: 'Samsung Galaxy A11',
    price: null,
    releasedDate: 'Released 2020, May 01',
    batteryCapacity: '4000',
    cpu: '720 x 1560 pixels, 19.5:9 ratio (~268 ppi density)',
    ram: '2/3',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~81.6% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/1.8, 27mm (wide), AF<br>\n5 MP, f/2.2, 115˚ (ultrawide)<br>\n2 MP, f/2.4, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m31-sm-m315f.jpg',
    modelName: 'Samsung Galaxy M31',
    price: null,
    releasedDate: 'Released 2020, March 05',
    batteryCapacity: '6000',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~403 ppi density)',
    ram: '6/8',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~84.1% screen-to-body ratio)',
    frontCameraRes:
     '64 MP, f/1.8, 26mm (wide), 1/1.72", 0.8µm, PDAF<br>\n8 MP, f/2.2, 123˚ (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.4, (macro)<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED, 420 nits (peak)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-ultra-.jpg',
    modelName: 'Samsung Galaxy S20 Ultra 5G',
    price: null,
    releasedDate: 'Released 2020, March 06',
    batteryCapacity: '5000',
    cpu: '1440 x 3200 pixels, 20:9 ratio (~511 ppi density)',
    ram: '12/16',
    sim: 'not found',
    screenSize:
     '6.9 inches, 114.0 cm<sup>2</sup> (~89.9% screen-to-body ratio)',
    frontCameraRes:
     '108 MP, f/1.8, 26mm (wide), 1/1.33", 0.8µm, PDAF, OIS<br>\n48 MP, f/3.5, 103mm (periscope telephoto), 1/2.0", 0.8µm, PDAF, OIS, 4x optical zoom, 10x hybrid zoom<br>\n12 MP, f/2.2, 13mm (ultrawide), 1.4µm, Super Steady video<br>\n0.3 MP, TOF 3D, f/1.0, (depth)',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'Dynamic AMOLED 2X, 120Hz, HDR10+, 1400 nits (peak)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-ultra-.jpg',
    modelName: 'Samsung Galaxy S20 Ultra',
    price: null,
    releasedDate: 'Released 2020, March 15',
    batteryCapacity: '5000',
    cpu: '1440 x 3200 pixels, 20:9 ratio (~511 ppi density)',
    ram: '12',
    sim: 'not found',
    screenSize:
     '6.9 inches, 114.0 cm<sup>2</sup> (~89.9% screen-to-body ratio)',
    frontCameraRes:
     '108 MP, f/1.8, 26mm (wide), 1/1.33", 0.8µm, PDAF, OIS<br>\n48 MP, f/3.5, 103mm (periscope telephoto), 1/2.0", 0.8µm, PDAF, OIS, 4x optical zoom, 10x hybrid zoom<br>\n12 MP, f/2.2, 13mm (ultrawide), 1.4µm, Super Steady video<br>\n0.3 MP, TOF 3D, f/1.0, (depth)',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'Dynamic AMOLED 2X, 120Hz, HDR10+, 1400 nits (peak)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-plus.jpg',
    modelName: 'Samsung Galaxy S20+ 5G',
    price: null,
    releasedDate: 'Released 2020, March 06',
    batteryCapacity: '4500',
    cpu: '1440 x 3200 pixels, 20:9 ratio (~525 ppi density)',
    ram: '12',
    sim: 'not found',
    screenSize:
     '6.7 inches, 108.0 cm<sup>2</sup> (~90.5% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS<br>\n64 MP, f/2.0, 29mm (telephoto), 1/1.72", 0.8µm, PDAF, OIS, 1.1x optical zoom, 3x hybrid zoom<br>\n12 MP, f/2.2, 13mm (ultrawide), 1.4µm, Super Steady video<br>\n0.3 MP, TOF 3D, f/1.0, (depth)',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'Dynamic AMOLED 2X, 120Hz, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-plus.jpg',
    modelName: 'Samsung Galaxy S20+',
    price: null,
    releasedDate: 'Released 2020, March 06',
    batteryCapacity: '4500',
    cpu: '1440 x 3200 pixels, 20:9 ratio (~525 ppi density)',
    ram: '8',
    sim: 'not found',
    screenSize:
     '6.7 inches, 108.0 cm<sup>2</sup> (~90.5% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS<br>\n64 MP, f/2.0, 29mm (telephoto), 1/1.72", 0.8µm, PDAF, OIS, 1.1x optical zoom, 3x hybrid zoom<br>\n12 MP, f/2.2, 13mm (ultrawide), 1.4µm, Super Steady video<br>\n0.3 MP, TOF 3D, f/1.0, (depth)',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'Dynamic AMOLED 2X, 120Hz, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-.jpg',
    modelName: 'Samsung Galaxy S20 5G UW',
    price: null,
    releasedDate: 'Released 2020, June 04',
    batteryCapacity: '4000',
    cpu: '1440 x 3200 pixels, 20:9 ratio (~566 ppi density)',
    ram: '8',
    sim: 'not found',
    screenSize:
     '6.2 inches, 92.8 cm<sup>2</sup> (~88.5% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS<br>\n64 MP, f/2.0, 29mm (telephoto), 1/1.72", 0.8µm, PDAF, OIS, 1.1x optical zoom, 3x hybrid zoom<br>\n12 MP, f/2.2, 13mm (ultrawide), 1.4µm, Super Steady video',
    rearCameraRes: 'No',
    os: 'Dynamic AMOLED 2X, 120Hz, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-.jpg',
    modelName: 'Samsung Galaxy S20 5G',
    price: null,
    releasedDate: 'Released 2020, March 06',
    batteryCapacity: '4000',
    cpu: '1440 x 3200 pixels, 20:9 ratio (~563 ppi density)',
    ram: '8/12',
    sim: 'not found',
    screenSize:
     '6.2 inches, 93.8 cm<sup>2</sup> (~89.5% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS<br>\n64 MP, f/2.0, 29mm (telephoto), 1/1.72", 0.8µm, PDAF, OIS, 1.1x optical zoom, 3x hybrid zoom<br>\n12 MP, f/2.2, 13mm (ultrawide), 1.4µm, Super Steady video',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'Dynamic AMOLED 2X, 120Hz, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s20-.jpg',
    modelName: 'Samsung Galaxy S20',
    price: null,
    releasedDate: 'Released 2020, March 06',
    batteryCapacity: '4000',
    cpu: '1440 x 3200 pixels, 20:9 ratio (~563 ppi density)',
    ram: '8',
    sim: 'not found',
    screenSize:
     '6.2 inches, 93.8 cm<sup>2</sup> (~89.5% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.8, 26mm (wide), 1/1.76", 1.8µm, Dual Pixel PDAF, OIS<br>\n64 MP, f/2.0, 29mm (telephoto), 1/1.72", 0.8µm, PDAF, OIS, 1.1x optical zoom, 3x hybrid zoom<br>\n12 MP, f/2.2, 13mm (ultrawide), 1.4µm, Super Steady video',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'Dynamic AMOLED 2X, 120Hz, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-z-flip-01.jpg',
    modelName: 'Samsung Galaxy Z Flip',
    price: null,
    releasedDate: 'Released 2020, February 14',
    batteryCapacity: '3300',
    cpu: '1080 x 2636 pixels (~425 ppi density)',
    ram: '8',
    sim: 'not found',
    screenSize:
     '6.7 inches, 101.6 cm<sup>2</sup> (~82.5% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.8, 27mm (wide), 1/2.55", 1.4µm, Dual Pixel PDAF, OIS<br>\n12 MP, f/2.2, 123˚ (ultrawide), 1.12µm',
    rearCameraRes: 'No',
    os: 'Foldable Dynamic AMOLED, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s6-5g-sm-t866n.jpg',
    modelName: 'Samsung Galaxy Tab S6 5G',
    price: null,
    releasedDate: 'Released 2020, January 30',
    batteryCapacity: '7040',
    cpu: '1600 x 2560 pixels, 16:10 ratio (~287 ppi density)',
    ram: '6',
    sim: 'not found',
    screenSize:
     '10.5 inches, 321.9 cm<sup>2</sup> (~82.5% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/2.0, 26mm (wide), 1/3.4", 1.0µm, AF<br>\n5 MP, f/2.2, 12mm (ultrawide), 1.12µm',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover-pro-.jpg',
    modelName: 'Samsung Galaxy Xcover Pro',
    price: null,
    releasedDate: 'Released 2020, January',
    batteryCapacity: '4050',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~409 ppi density)',
    ram: '4',
    sim: 'not found',
    screenSize:
     '6.3 inches, 97.4 cm<sup>2</sup> (~79.4% screen-to-body ratio)',
    frontCameraRes:
     '25 MP, f/1.7, 26mm (wide), PDAF<br>\n8 MP, f/2.2, 123˚ (ultrawide), 1/4.0", 1.12µm',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'IPS LCD ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/sasmung-galaxy-note10-lite-r.jpg',
    modelName: 'Samsung Galaxy Note10 Lite',
    price: null,
    releasedDate: 'Released 2020, January 21',
    batteryCapacity: '4500',
    cpu: '1080 x 2400 pixels, 20:9 ratio (~394 ppi density)',
    ram: '6/8',
    sim: 'not found',
    screenSize:
     '6.7 inches, 107.8 cm<sup>2</sup> (~86.6% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.7, 27mm (wide), 1/2.55", 1.4µm, Dual Pixel PDAF, OIS<br>\n12 MP, f/2.4, 52mm (telephoto), 1/3.6", 1.0µm, PDAF, OIS, 2x optical zoom<br>\n12 MP, f/2.2, 12mm (ultrawide)',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'Super AMOLED, HDR',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/sasmung-galaxy-s10-lite-.jpg',
    modelName: 'Samsung Galaxy S10 Lite',
    price: null,
    releasedDate: 'Released 2020, February 03',
    batteryCapacity: '4500',
    cpu: '1080 x 2400 pixels, 20:9 ratio (~394 ppi density)',
    ram: '6/8',
    sim: 'not found',
    screenSize:
     '6.7 inches, 107.8 cm<sup>2</sup> (~87.8% screen-to-body ratio)',
    frontCameraRes:
     '48 MP, f/2.0, 26mm (wide), 1/2.0", 0.8µm, PDAF, Super Steady OIS<br>\n12 MP, f/2.2, 12mm (ultrawide)<br>\n5 MP, f/2.4, (macro)',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'Super AMOLED Plus, HDR10+',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a01.jpg',
    modelName: 'Samsung Galaxy A01',
    price: null,
    releasedDate: 'Released 2020, January',
    batteryCapacity: '3000',
    cpu: '720 x 1520 pixels, 19:9 ratio (~294 ppi density)',
    ram: '2',
    sim: 'not found',
    screenSize:
     '5.7 inches, 81.6 cm<sup>2</sup> (~78.8% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/2.2, 28mm (wide), 1/3.1", 1.12µm, AF<br>\n2 MP, f/2.4, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a71.jpg',
    modelName: 'Samsung Galaxy A71',
    price: null,
    releasedDate: 'Released 2020, January 17',
    batteryCapacity: '4500',
    cpu: '1080 x 2400 pixels, 20:9 ratio (~393 ppi density)',
    ram: '6/8',
    sim: 'not found',
    screenSize:
     '6.7 inches, 108.4 cm<sup>2</sup> (~87.2% screen-to-body ratio)',
    frontCameraRes:
     '64 MP, f/1.8, 26mm (wide), 1/1.72", 0.8µm, PDAF<br>\n12 MP, f/2.2, 123˚ (ultrawide)<br>\n5 MP, f/2.4, (macro)<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED Plus ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a51-sm-a515.jpg',
    modelName: 'Samsung Galaxy A51',
    price: null,
    releasedDate: 'Released 2019, December 16',
    batteryCapacity: '4000',
    cpu: '1080 x 2400 pixels, 20:9 ratio (~405 ppi density)',
    ram: '4-8',
    sim: 'not found',
    screenSize:
     '6.5 inches, 102.0 cm<sup>2</sup> (~87.4% screen-to-body ratio)',
    frontCameraRes:
     '48 MP, f/2.0, 26mm (wide), 1/2.0", 0.8µm, PDAF<br>\n12 MP, f/2.2, 123˚ (ultrawide)<br>\n5 MP, f/2.4, (macro)<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover-fieldpro-sm-g889f.jpg',
    modelName: 'Samsung Galaxy Xcover FieldPro',
    price: null,
    releasedDate: 'Released 2020, April 06',
    batteryCapacity: '4500',
    cpu: '1440 x 2560 pixels, 16:9 ratio (~576 ppi density)',
    ram: '4',
    sim: 'not found',
    screenSize:
     '5.1 inches, 71.7 cm<sup>2</sup> (~56.1% screen-to-body ratio)',
    frontCameraRes: '12 MP, f/1.5-2.4, (wide), 1/2.55", 1.4µm, PDAF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'IPS LCD ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a70s-.jpg',
    modelName: 'Samsung Galaxy A70s',
    price: null,
    releasedDate: 'Released 2019, September',
    batteryCapacity: '4500',
    cpu: '1080 x 2400 pixels, 20:9 ratio (~393 ppi density)',
    ram: '6/8',
    sim: 'not found',
    screenSize:
     '6.7 inches, 108.4 cm<sup>2</sup> (~86.0% screen-to-body ratio)',
    frontCameraRes:
     '64 MP, f/1.8, 26mm (wide), 1/1.72", 0.8µm, PDAF<br>\n8 MP, f/2.2, 12mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a20s-sm-a207.jpg',
    modelName: 'Samsung Galaxy A20s',
    price: null,
    releasedDate: 'Released 2019, October 05',
    batteryCapacity: '4000',
    cpu: '720 x 1560 pixels, 19.5:9 ratio (~264 ppi density)',
    ram: '2-4',
    sim: 'not found',
    screenSize:
     '6.5 inches, 103.7 cm<sup>2</sup> (~81.9% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/1.8, 27mm (wide), PDAF<br>\n8 MP, f/2.2, 13mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'IPS LCD ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m30s-.jpg',
    modelName: 'Samsung Galaxy M30s',
    price: null,
    releasedDate: 'Released 2019, October 30',
    batteryCapacity: '6000',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~403 ppi density)',
    ram: '4/6',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~84.2% screen-to-body ratio)',
    frontCameraRes:
     '48 MP, f/2.0, 26mm (wide), 1/2.0", 0.8µm, PDAF<br>\n8 MP, f/2.2, 12mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED, 420 nits (typ)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m10s-m107f.jpg',
    modelName: 'Samsung Galaxy M10s',
    price: null,
    releasedDate: 'Released 2019, September',
    batteryCapacity: '4000',
    cpu: '720 x 1560 pixels, 19.5:9 ratio (~268 ppi density)',
    ram: '3',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~85.0% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/1.9, 27mm (wide), 1/3.1", 1.12µm, PDAF<br>\n5 MP, f/2.2, 12mm (ultrawide)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-fold-5g.jpg',
    modelName: 'Samsung Galaxy Fold 5G',
    price: null,
    releasedDate: 'Released 2019, September',
    batteryCapacity: '4235',
    cpu: '1536 x 2152 pixels (~362 ppi density)',
    ram: '12',
    sim: 'not found',
    screenSize:
     '7.3 inches, 162.6 cm<sup>2</sup> (~85.7% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.5-2.4, 27mm (wide), 1/2.55", 1.4µm, Dual Pixel PDAF, OIS<br>\n12 MP, f/2.4, 52mm (telephoto), 1/3.6", 1.0µm, AF, OIS, 2x optical zoom<br>\n16 MP, f/2.2, 12mm (ultrawide), 1/3.1", 1.0µm',
    rearCameraRes: 'No',
    os: 'Foldable Dynamic AMOLED, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-fold.jpg',
    modelName: 'Samsung Galaxy Fold',
    price: null,
    releasedDate: 'Released 2019, September',
    batteryCapacity: '4380',
    cpu: '1536 x 2152 pixels (~362 ppi density)',
    ram: '12',
    sim: 'not found',
    screenSize:
     '7.3 inches, 162.6 cm<sup>2</sup> (~85.7% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.5-2.4, 27mm (wide), 1/2.55", 1.4µm, Dual Pixel PDAF, OIS<br>\n12 MP, f/2.4, 52mm (telephoto), 1/3.6", 1.0µm, AF, OIS, 2x optical zoom<br>\n16 MP, f/2.2, 12mm (ultrawide), 1/3.1", 1.0µm',
    rearCameraRes: 'No',
    os: 'Foldable Dynamic AMOLED, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-active-pro-sm-t547.jpg',
    modelName: 'Samsung Galaxy Tab Active Pro',
    price: null,
    releasedDate: 'Released 2019, October',
    batteryCapacity: '7600',
    cpu: '1920 x 1200 pixels, 16:10 ratio (~224 ppi density)',
    ram: '4',
    sim: 'not found',
    screenSize:
     '10.1 inches, 295.8 cm<sup>2</sup> (~71.4% screen-to-body ratio)',
    frontCameraRes: '13 MP, AF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'LCD, 550 nits (typ)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a90-5g.jpg',
    modelName: 'Samsung Galaxy A90 5G',
    price: null,
    releasedDate: 'Released 2019, September',
    batteryCapacity: '4500',
    cpu: '1080 x 2400 pixels, 20:9 ratio (~393 ppi density)',
    ram: '6/8',
    sim: 'not found',
    screenSize:
     '6.7 inches, 108.4 cm<sup>2</sup> (~86.1% screen-to-body ratio)',
    frontCameraRes:
     '48 MP, f/2.0, 26mm (wide), 1/2.0", 0.8µm, PDAF<br>\n8 MP, f/2.2, 12mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (6GB model only)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a30s.jpg',
    modelName: 'Samsung Galaxy A30s',
    price: null,
    releasedDate: 'Released 2019, September 11',
    batteryCapacity: '4000',
    cpu: '720 x 1560 pixels, 19.5:9 ratio (~268 ppi density)',
    ram: '3/4',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~84.9% screen-to-body ratio)',
    frontCameraRes:
     '25 MP, f/1.7, 27mm (wide), PDAF<br>\n8 MP, f/2.2, 13mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a50s.jpg',
    modelName: 'Samsung Galaxy A50s',
    price: null,
    releasedDate: 'Released 2019, September',
    batteryCapacity: '4000',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~403 ppi density)',
    ram: '4/6',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~85.1% screen-to-body ratio)',
    frontCameraRes:
     '48 MP, f/2.0, 26mm (wide), 1/2.0", 0.8µm, PDAF<br>\n8 MP, f/2.2, 13mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note10-plus-.jpg',
    modelName: 'Samsung Galaxy Note10+ 5G',
    price: null,
    releasedDate: 'Released 2019, August',
    batteryCapacity: '4300',
    cpu: '1440 x 3040 pixels, 19:9 ratio (~498 ppi density)',
    ram: '12',
    sim: 'not found',
    screenSize:
     '6.8 inches, 114.0 cm<sup>2</sup> (~91.0% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.5-2.4, 27mm (wide), 1/2.55", 1.4µm, Dual Pixel PDAF, OIS<br>\n12 MP, f/2.1, 52mm (telephoto), 1/3.6", 1.0µm, PDAF, OIS, 2x optical zoom<br>\n16 MP, f/2.2, 12mm (ultrawide), 1/3.1", 1.0µm, Super Steady video<br>\n0.3 MP, TOF 3D, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Dynamic AMOLED, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note10-plus-.jpg',
    modelName: 'Samsung Galaxy Note10+',
    price: null,
    releasedDate: 'Released 2019, August 23',
    batteryCapacity: '4300',
    cpu:
     'Glass front (Gorilla Glass 6), glass back (Gorilla Glass 6), aluminum frame',
    ram: '12',
    sim: 'HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 ',
    screenSize: '196 g (6.91 oz)',
    frontCameraRes: 'microSDXC (uses shared SIM slot) - dual SIM model only',
    rearCameraRes: 'Android 9.0 (Pie), upgradable to Android 10, One UI 2.5',
    os: '162.3 x 77.2 x 7.9 mm (6.39 x 3.04 x 0.31 in)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note10-.jpg',
    modelName: 'Samsung Galaxy Note10 5G',
    price: null,
    releasedDate: 'Released 2019, August',
    batteryCapacity: '3500',
    cpu: '1080 x 2280 pixels, 19:9 ratio (~401 ppi density)',
    ram: '12',
    sim: 'not found',
    screenSize:
     '6.3 inches, 98.6 cm<sup>2</sup> (~90.9% screen-to-body ratio)',
    frontCameraRes:
     '12 MP, f/1.5-2.4, 27mm (wide), 1/2.55", 1.4µm, Dual Pixel PDAF, OIS<br>\n12 MP, f/2.1, 52mm (telephoto), 1/3.6", 1.0µm, PDAF, OIS, 2x optical zoom<br>\n16 MP, f/2.2, 12mm (ultrawide), 1/3.1", 1.0µm, Super Steady video',
    rearCameraRes: 'No',
    os: 'Dynamic AMOLED, HDR10+',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note10-.jpg',
    modelName: 'Samsung Galaxy Note10',
    price: null,
    releasedDate: 'Released 2019, August 23',
    batteryCapacity: '3500',
    cpu:
     'Glass front (Gorilla Glass 6), glass back (Gorilla Glass 6), aluminum frame',
    ram: '8',
    sim: 'HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 ',
    screenSize: '168 g (5.93 oz)',
    frontCameraRes: 'No',
    rearCameraRes: 'Android 9.0 (Pie), upgradable to Android 10, One UI 2.5',
    os: '151 x 71.8 x 7.9 mm (5.94 x 2.83 x 0.31 in)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch-active2-stainless-steel.jpg',
    modelName: 'Samsung Galaxy Watch Active2',
    price: null,
    releasedDate: 'Released 2019, September',
    batteryCapacity: '340',
    cpu:
     'Glass front (Gorilla Glass DX+), stainless steel frame 316L',
    ram: '1.5',
    sim: 'HSDPA 850 / 1700(AWS) / 1900 - USA/Canada',
    screenSize: '42 g (1.48 oz)',
    frontCameraRes: 'No',
    rearCameraRes: 'Tizen-based wearable OS 4.0',
    os: '44 x 44 x 10.9 mm (1.73 x 1.73 x 0.43 in)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch-active2-.jpg',
    modelName: 'Samsung Galaxy Watch Active2 Aluminum',
    price: null,
    releasedDate: 'Released 2019, September',
    batteryCapacity: '340',
    cpu: 'Glass front (Gorilla Glass DX+), aluminum frame',
    ram: '768',
    sim: '1, 3, 7, 8, 20 - 44mm LTE version only',
    screenSize: '30 g (1.06 oz)',
    frontCameraRes: 'No',
    rearCameraRes: 'Tizen-based wearable OS 4.0',
    os: '44 x 44 x 10.9 mm (1.73 x 1.73 x 0.43 in)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a10s.jpg',
    modelName: 'Samsung Galaxy A10s',
    price: null,
    releasedDate: 'Released 2019, August 27',
    batteryCapacity: '4000',
    cpu: '720 x 1520 pixels, 19:9 ratio (~271 ppi density)',
    ram: '2/3',
    sim: 'not found',
    screenSize:
     '6.2 inches, 95.9 cm<sup>2</sup> (~80.7% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/1.8, 28mm (wide), AF<br>\n2 MP, f/2.4, (depth)<br>\n',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a10e-sm-a102u.jpg',
    modelName: 'Samsung Galaxy A10e',
    price: null,
    releasedDate: 'Released 2019, August',
    batteryCapacity: '3000',
    cpu: 'Glass front, plastic back, plastic frame',
    ram: '2',
    sim: 'HSDPA 850 / 1700(AWS) / 1900 / 2100 - AT&amp;T',
    screenSize: '141 g (4.97 oz)',
    frontCameraRes: 'microSDXC (dedicated slot)',
    rearCameraRes: 'Android 9.0 (Pie)',
    os: '147.3 x 69.6 x 8.4 mm (5.80 x 2.74 x 0.33 in)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s6.jpg',
    modelName: 'Samsung Galaxy Tab S6',
    price: null,
    releasedDate: 'Released 2019, August',
    batteryCapacity: '7040',
    cpu: '1600 x 2560 pixels, 16:10 ratio (~287 ppi density)',
    ram: '6/8',
    sim: 'not found',
    screenSize:
     '10.5 inches, 321.9 cm<sup>2</sup> (~82.5% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/2.0, 26mm (wide), 1/3.4", 1.0µm, AF<br>\n5 MP, f/2.2, 12mm (ultrawide), 1.12µm',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a-80-2019-r.jpg',
    modelName: 'Samsung Galaxy Tab A 8.0 (2019)',
    price: null,
    releasedDate: 'Released 2019, July',
    batteryCapacity: '5100',
    cpu: '800 x 1280 pixels, 16:10 ratio (~189 ppi density)',
    ram: '2',
    sim: 'not found',
    screenSize:
     '8.0 inches, 185.6 cm<sup>2</sup> (~71.0% screen-to-body ratio)',
    frontCameraRes: '8 MP, AF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover-4s-sm-g398.jpg',
    modelName: 'Samsung Galaxy Xcover 4s',
    price: null,
    releasedDate: 'Released 2019, July',
    batteryCapacity: '2800',
    cpu: '720 x 1280 pixels, 16:9 ratio (~294 ppi density)',
    ram: '3',
    sim: 'not found',
    screenSize:
     '5.0 inches, 68.9 cm<sup>2</sup> (~64.3% screen-to-body ratio)',
    frontCameraRes: '16 MP, f/1.7, PDAF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a2-core-sm-a260f.jpg',
    modelName: 'Samsung Galaxy A2 Core',
    price: null,
    releasedDate: 'Released 2019, April',
    batteryCapacity: '2600',
    cpu: '540 x 960 pixels, 16:9 ratio (~220 ppi density)',
    ram: '1',
    sim: 'not found',
    screenSize:
     '5.0 inches, 68.9 cm<sup>2</sup> (~68.6% screen-to-body ratio)',
    frontCameraRes: '5 MP, f/1.9, AF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-watch-active.jpg',
    modelName: 'Samsung Galaxy Watch Active',
    price: null,
    releasedDate: 'Released 2019, April',
    batteryCapacity: '230',
    cpu: 'Dual-core 1.15 GHz Cortex-A53',
    ram: '768',
    sim:
     'Samsung Pay<br>\n50m water resistant (IP68)<br>\nCompatible with standard 20mm straps<br>\nMIL-STD-810G compliant*<br>\n*does not guarantee ruggedness or use in extreme conditions',
    screenSize: 'Exynos 9110 (10 nm)',
    frontCameraRes: 'Yes',
    rearCameraRes: 'No',
    os: 'Tizen-based wearable OS 4.0',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-view2-sm-t927--.jpg',
    modelName: 'Samsung Galaxy View2',
    price: null,
    releasedDate: 'Released 2019, April',
    batteryCapacity: '12000',
    cpu: '1080 x 1920 pixels, 16:9 ratio (~127 ppi density)',
    ram: '3',
    sim: 'not found',
    screenSize:
     '17.3 inches, 825.1 cm<sup>2</sup> (~75.1% screen-to-body ratio)',
    frontCameraRes: 'No',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'IPS LCD ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s10-5g.jpg',
    modelName: 'Samsung Galaxy S10 5G',
    price: null,
    releasedDate: 'Released 2019, April',
    batteryCapacity: '4500',
    cpu:
     'Glass front (Gorilla Glass 6), glass back (Gorilla Glass 6), aluminum frame',
    ram: '8',
    sim: 'HSDPA 850 / 900 / 1900 / 2100 - USA',
    screenSize: '198 g (6.98 oz)',
    frontCameraRes: 'No',
    rearCameraRes: 'Android 9.0 (Pie), upgradable to Android 10, One UI 2',
    os: '162.6 x 77.1 x 7.9 mm (6.40 x 3.04 x 0.31 in)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s10-plus-new.jpg',
    modelName: 'Samsung Galaxy S10+',
    price: null,
    releasedDate: 'Released 2019, March 08',
    batteryCapacity: '4100',
    cpu:
     'Glass front (Gorilla Glass 6), glass back (Gorilla Glass 5), aluminum frame<br>Glass front (Gorilla Glass 6), ceramic back, ceramic frame',
    ram: '8/12',
    sim: 'HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 - Global, USA',
    screenSize: '175 g / 198 g (ceramic) (6.17 oz)',
    frontCameraRes: 'microSDXC (uses shared SIM slot) - dual SIM model only',
    rearCameraRes: 'Android 9.0 (Pie), upgradable to Android 10, One UI 2',
    os: '157.6 x 74.1 x 7.8 mm (6.20 x 2.92 x 0.31 in)',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s10.jpg',
    modelName: 'Samsung Galaxy S10',
    price: null,
    releasedDate: 'Released 2019, March 08',
    batteryCapacity: '3400',
    cpu:
     'Glass front (Gorilla Glass 6), glass back (Gorilla Glass 5), aluminum frame',
    ram: '8',
    sim: 'HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 - Global, USA',
    screenSize: '157 g (5.54 oz)',
    frontCameraRes: 'microSDXC (uses shared SIM slot) - dual SIM model only',
    rearCameraRes: 'Android 9.0 (Pie), upgradable to Android 10, One UI 2.1',
    os: '149.9 x 70.4 x 7.8 mm (5.90 x 2.77 x 0.31 in)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s10e.jpg',
    modelName: 'Samsung Galaxy S10e',
    price: null,
    releasedDate: 'Released 2019, March 08',
    batteryCapacity: '3100',
    cpu:
     'Glass front (Gorilla Glass 5), glass back (Gorilla Glass 5), aluminum frame',
    ram: '6/8',
    sim: 'HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100 - Global, USA',
    screenSize: '150 g (5.29 oz)',
    frontCameraRes: 'microSDXC (uses shared SIM slot) - dual SIM model only',
    rearCameraRes: 'Android 9.0 (Pie), upgradable to Android 10, One UI 2',
    os: '142.2 x 69.9 x 7.9 mm (5.60 x 2.75 x 0.31 in)',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m40-m405f.jpg',
    modelName: 'Samsung Galaxy M40',
    price: null,
    releasedDate: 'Released 2019, June',
    batteryCapacity: '3500',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~409 ppi density)',
    ram: '4/6',
    sim: 'not found',
    screenSize:
     '6.3 inches, 97.4 cm<sup>2</sup> (~84.9% screen-to-body ratio)',
    frontCameraRes:
     '32 MP, f/1.7, 26mm (wide), 1/2.8", 0.8µm, PDAF<br>\n8 MP, f/2.2, 12mm (ultrawide), 1/4.0", 1.12µm, PDAF<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m30-.jpg',
    modelName: 'Samsung Galaxy M30',
    price: null,
    releasedDate: 'Released 2019, March',
    batteryCapacity: '5000',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~403 ppi density)',
    ram: '3-6',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~84.2% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/1.9, PDAF<br>\n5 MP, f/2.2, 12mm (ultrawide)<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m20-m205f.jpg',
    modelName: 'Samsung Galaxy M20',
    price: null,
    releasedDate: 'Released 2019, February',
    batteryCapacity: '5000',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~409 ppi density)',
    ram: '3/4',
    sim: 'not found',
    screenSize:
     '6.3 inches, 97.4 cm<sup>2</sup> (~83.6% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/1.9, 1/3.1", 1.12µm, PDAF<br>\n5 MP, f/2.2, 12mm (ultrawide)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-m10-m105f.jpg',
    modelName: 'Samsung Galaxy M10',
    price: null,
    releasedDate: 'Released 2019, February',
    batteryCapacity: '3400',
    cpu: '720 x 1520 pixels, 19:9 ratio (~270 ppi density)',
    ram: '2/3',
    sim: 'not found',
    screenSize:
     '6.22 inches, 96.6 cm<sup>2</sup> (~82.1% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/1.9, 27mm (wide), 1/3.1", 1.12µm, PDAF<br>\n5 MP, f/2.2, 12mm (ultrawide)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a80-.jpg',
    modelName: 'Samsung Galaxy A80',
    price: null,
    releasedDate: 'Released 2019, May',
    batteryCapacity: '3700',
    cpu: '1080 x 2400 pixels, 20:9 ratio (~393 ppi density)',
    ram: '8',
    sim: 'not found',
    screenSize:
     '6.7 inches, 108.4 cm<sup>2</sup> (~85.8% screen-to-body ratio)',
    frontCameraRes:
     '48 MP, f/2.0, 26mm (wide), 1/2.0", 0.8µm, PDAF<br>\n8 MP, f/2.2, 12mm (ultrawide), 1/4.0", 1.12µm<br>\nTOF 3D, f/1.2, (depth)',
    rearCameraRes: 'No',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a70.jpg',
    modelName: 'Samsung Galaxy A70',
    price: null,
    releasedDate: 'Released 2019, May 01',
    batteryCapacity: '4500',
    cpu: '1080 x 2400 pixels, 20:9 ratio (~393 ppi density)',
    ram: '6/8',
    sim: 'not found',
    screenSize:
     '6.7 inches, 108.4 cm<sup>2</sup> (~86.0% screen-to-body ratio)',
    frontCameraRes:
     '32 MP, f/1.7, 26mm (wide), 1/2.8", 0.8µm, PDAF<br>\n8 MP, f/2.2, 12mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a60-.jpg',
    modelName: 'Samsung Galaxy A60',
    price: null,
    releasedDate: 'Released 2019, June',
    batteryCapacity: '3500',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~409 ppi density)',
    ram: '6',
    sim: 'not found',
    screenSize:
     '6.3 inches, 97.4 cm<sup>2</sup> (~84.9% screen-to-body ratio)',
    frontCameraRes:
     '32 MP, f/1.7, 26mm (wide), 1/2.8", 0.8µm, PDAF<br>\n8 MP, f/2.2, 12mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (uses shared SIM slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a50-sm-a505f-ds.jpg',
    modelName: 'Samsung Galaxy A50',
    price: null,
    releasedDate: 'Released 2019, March 18',
    batteryCapacity: '4000',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~403 ppi density)',
    ram: '4/6',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~84.9% screen-to-body ratio)',
    frontCameraRes:
     '25 MP, f/1.7, 26mm (wide), PDAF<br>\n8 MP, f/2.2, 13mm (ultrawide), 1/4.0", 1.12µm<br>\n5 MP, f/2.2, (depth)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a40.jpg',
    modelName: 'Samsung Galaxy A40',
    price: null,
    releasedDate: 'Released 2019, April',
    batteryCapacity: '3100',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~437 ppi density)',
    ram: '4',
    sim: 'not found',
    screenSize:
     '5.9 inches, 85.5 cm<sup>2</sup> (~85.5% screen-to-body ratio)',
    frontCameraRes:
     '16 MP, f/1.7, 26mm (wide), PDAF<br>\n5 MP, f/2.2, 13mm (ultrawide)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a30.jpg',
    modelName: 'Samsung Galaxy A30',
    price: null,
    releasedDate: 'Released 2019, March',
    batteryCapacity: '4000',
    cpu: '1080 x 2340 pixels, 19.5:9 ratio (~403 ppi density)',
    ram: '3/4',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~84.9% screen-to-body ratio)',
    frontCameraRes:
     '16 MP, f/1.7, 27mm (wide), PDAF<br>\n5 MP, f/2.2, 12mm, (ultrawide)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a20e.jpg',
    modelName: 'Samsung Galaxy A20e',
    price: null,
    releasedDate: 'Released 2019, May',
    batteryCapacity: '3000',
    cpu: '720 x 1560 pixels, 19.5:9 ratio (~296 ppi density)',
    ram: '3',
    sim: 'not found',
    screenSize:
     '5.8 inches, 82.6 cm<sup>2</sup> (~80.4% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/1.9, 28mm (wide), AF<br>\n5 MP, f/2.2, 12mm (ultrawide)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'PLS TFT ',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a20.jpg',
    modelName: 'Samsung Galaxy A20',
    price: null,
    releasedDate: 'Released 2019, April 05',
    batteryCapacity: '4000',
    cpu: '720 x 1560 pixels, 19.5:9 ratio (~268 ppi density)',
    ram: '3',
    sim: 'not found',
    screenSize:
     '6.4 inches, 100.5 cm<sup>2</sup> (~85.0% screen-to-body ratio)',
    frontCameraRes:
     '13 MP, f/1.9, 28mm (wide), AF<br>\n5 MP, f/2.2, 12mm (ultrawide)',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl: 'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a10.jpg',
    modelName: 'Samsung Galaxy A10',
    price: null,
    releasedDate: 'Released 2019, March 19',
    batteryCapacity: '3400',
    cpu: '720 x 1520 pixels, 19:9 ratio (~271 ppi density)',
    ram: '2/4',
    sim: 'not found',
    screenSize:
     '6.2 inches, 95.9 cm<sup>2</sup> (~81.6% screen-to-body ratio)',
    frontCameraRes: '13 MP, f/1.9, 28mm (wide), AF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'IPS LCD ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s5e-sm-t725.jpg',
    modelName: 'Samsung Galaxy Tab S5e',
    price: null,
    releasedDate: 'Released 2019, April',
    batteryCapacity: '7040',
    cpu: '1600 x 2560 pixels, 16:10 ratio (~288 ppi density)',
    ram: '4/6',
    sim: 'not found',
    screenSize:
     '10.5 inches, 319.7 cm<sup>2</sup> (~81.6% screen-to-body ratio)',
    frontCameraRes: '13 MP, f/2.0, 26mm, 1/3.4", 1.0µm, AF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'Super AMOLED ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a-101-2019.jpg',
    modelName: 'Samsung Galaxy Tab A 10.1 (2019)',
    price: null,
    releasedDate: 'Released 2019, April',
    batteryCapacity: '6150',
    cpu: '1200 x 1920 pixels, 16:10 ratio (~224 ppi density)',
    ram: '2/3',
    sim: 'not found',
    screenSize:
     '10.1 inches, 295.8 cm<sup>2</sup> (~80.7% screen-to-body ratio)',
    frontCameraRes: '8 MP, f/2.0, AF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'TFT ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a-s-pen-sm-p205.jpg',
    modelName: 'Samsung Galaxy Tab A 8.0 &amp; S Pen (2019)',
    price: null,
    releasedDate: 'Released 2019, April',
    batteryCapacity: '4200',
    cpu: '1200 x 1920 pixels, 16:10 ratio (~283 ppi density)',
    ram: '3',
    sim: 'not found',
    screenSize:
     '8.0 inches, 185.6 cm<sup>2</sup> (~75.2% screen-to-body ratio)',
    frontCameraRes: '8 MP, f/2.0, AF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'IPS LCD ',
    brandId: 'Samsung' },
  { imgUrl:
     'https://fdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-advanced2-sm-t583.jpg',
    modelName: 'Samsung Galaxy Tab Advanced2',
    price: null,
    releasedDate: 'Released 2018, December',
    batteryCapacity: '7300',
    cpu: '1200 x 1920 pixels, 16:10 ratio (~224 ppi density)',
    ram: '3',
    sim: 'not found',
    screenSize: '10.1 inches, 295.8 cm<sup>2</sup> (~71.1% screen-to-body ratio)',
    frontCameraRes: '8 MP, AF',
    rearCameraRes: 'microSDXC (dedicated slot)',
    os: 'IPS LCD ',
    brandId: 'Samsung' }].map((mobile)=>{
        if(mobile.brandId == "Apple") mobile.brandId = ObjectID("5fb3daa9133c9681449ca891");
        if(mobile.brandId == "Oppo") mobile.brandId = ObjectID("5fb684f96c02b306cec79e02");
        if(mobile.brandId == "Samsung") mobile.brandId = ObjectID("5fb3dad6133c9681449ca893");
        mobile.memory = "Internal:  128GB \n External: microSDXC"
        mobile.price = Math.floor(Math.random()*1000);
        mobile.batteryCapacity = parseInt(mobile.batteryCapacity);
        return mobile;
    });
